import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

/**
 * Generate the bundled models.dev snapshot.
 *
 * The catalog is vendored at `vendor/models-dev.json` so builds — and the
 * deployments they produce — never need to reach models.dev. Set
 * MODELS_DEV_REFRESH=1 to pull a fresh copy from the network and rewrite the
 * vendored file; that is a maintenance step, not part of a normal build.
 */
const VENDORED = path.join(dir, "vendor/models-dev.json")

const modelsUrl = process.env.RAVENS_MODELS_URL || "https://models.dev"
const refresh = process.env.MODELS_DEV_REFRESH === "1" || process.env.MODELS_DEV_REFRESH === "true"

async function readVendored() {
  const file = Bun.file(VENDORED)
  if (!(await file.exists())) return undefined
  return file.text()
}

const modelsData = await (async () => {
  // An explicit path always wins — it's how tests and air-gapped builds inject
  // their own catalog.
  if (process.env.MODELS_DEV_API_JSON) return Bun.file(process.env.MODELS_DEV_API_JSON).text()

  if (!refresh) {
    const vendored = await readVendored()
    if (vendored) return vendored
    console.warn(`No vendored catalog at ${VENDORED}; falling back to ${modelsUrl}`)
  }

  const fetched = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  // Keep the vendored copy in step so the next offline build has the update.
  await Bun.write(VENDORED, fetched)
  console.log(`Refreshed ${path.relative(dir, VENDORED)} from ${modelsUrl}`)
  return fetched
})()

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
