import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const RAVENS_EXPERIMENTAL = truthy("RAVENS_EXPERIMENTAL")
const RAVENS_DISABLE_CLAUDE_CODE = truthy("RAVENS_DISABLE_CLAUDE_CODE")
const RAVENS_DISABLE_CLAUDE_CODE_SKILLS =
  RAVENS_DISABLE_CLAUDE_CODE || truthy("RAVENS_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["RAVENS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  RAVENS_AUTO_SHARE: truthy("RAVENS_AUTO_SHARE"),
  RAVENS_AUTO_HEAP_SNAPSHOT: truthy("RAVENS_AUTO_HEAP_SNAPSHOT"),
  RAVENS_GIT_BASH_PATH: process.env["RAVENS_GIT_BASH_PATH"],
  RAVENS_CONFIG: process.env["RAVENS_CONFIG"],
  RAVENS_CONFIG_CONTENT: process.env["RAVENS_CONFIG_CONTENT"],
  RAVENS_DISABLE_AUTOUPDATE: truthy("RAVENS_DISABLE_AUTOUPDATE"),
  RAVENS_ALWAYS_NOTIFY_UPDATE: truthy("RAVENS_ALWAYS_NOTIFY_UPDATE"),
  RAVENS_DISABLE_PRUNE: truthy("RAVENS_DISABLE_PRUNE"),
  RAVENS_DISABLE_TERMINAL_TITLE: truthy("RAVENS_DISABLE_TERMINAL_TITLE"),
  RAVENS_SHOW_TTFD: truthy("RAVENS_SHOW_TTFD"),
  RAVENS_PERMISSION: process.env["RAVENS_PERMISSION"],
  RAVENS_DISABLE_DEFAULT_PLUGINS: truthy("RAVENS_DISABLE_DEFAULT_PLUGINS"),
  RAVENS_DISABLE_LSP_DOWNLOAD: truthy("RAVENS_DISABLE_LSP_DOWNLOAD"),
  RAVENS_ENABLE_EXPERIMENTAL_MODELS: truthy("RAVENS_ENABLE_EXPERIMENTAL_MODELS"),
  RAVENS_DISABLE_AUTOCOMPACT: truthy("RAVENS_DISABLE_AUTOCOMPACT"),
  RAVENS_DISABLE_MODELS_FETCH: truthy("RAVENS_DISABLE_MODELS_FETCH"),
  RAVENS_DISABLE_MOUSE: truthy("RAVENS_DISABLE_MOUSE"),
  RAVENS_DISABLE_CLAUDE_CODE,
  RAVENS_DISABLE_CLAUDE_CODE_PROMPT: RAVENS_DISABLE_CLAUDE_CODE || truthy("RAVENS_DISABLE_CLAUDE_CODE_PROMPT"),
  RAVENS_DISABLE_CLAUDE_CODE_SKILLS,
  RAVENS_DISABLE_EXTERNAL_SKILLS: truthy("RAVENS_DISABLE_EXTERNAL_SKILLS"),
  RAVENS_FAKE_VCS: process.env["RAVENS_FAKE_VCS"],
  RAVENS_SERVER_PASSWORD: process.env["RAVENS_SERVER_PASSWORD"],
  RAVENS_SERVER_USERNAME: process.env["RAVENS_SERVER_USERNAME"],
  RAVENS_ENABLE_QUESTION_TOOL: truthy("RAVENS_ENABLE_QUESTION_TOOL"),

  // Experimental
  RAVENS_EXPERIMENTAL,
  RAVENS_EXPERIMENTAL_FILEWATCHER: Config.boolean("RAVENS_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  RAVENS_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("RAVENS_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  RAVENS_EXPERIMENTAL_ICON_DISCOVERY: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_ICON_DISCOVERY"),
  RAVENS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("RAVENS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  RAVENS_ENABLE_EXA: truthy("RAVENS_ENABLE_EXA") || RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_EXA"),
  RAVENS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("RAVENS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  RAVENS_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("RAVENS_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  RAVENS_EXPERIMENTAL_OXFMT: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_OXFMT"),
  RAVENS_EXPERIMENTAL_LSP_TY: truthy("RAVENS_EXPERIMENTAL_LSP_TY"),
  RAVENS_EXPERIMENTAL_LSP_TOOL: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_LSP_TOOL"),
  RAVENS_EXPERIMENTAL_PLAN_MODE: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_PLAN_MODE"),
  RAVENS_EXPERIMENTAL_SCOUT: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_SCOUT"),
  RAVENS_EXPERIMENTAL_MARKDOWN: !falsy("RAVENS_EXPERIMENTAL_MARKDOWN"),
  RAVENS_ENABLE_PARALLEL: truthy("RAVENS_ENABLE_PARALLEL") || truthy("RAVENS_EXPERIMENTAL_PARALLEL"),
  RAVENS_MODELS_URL: process.env["RAVENS_MODELS_URL"],
  RAVENS_MODELS_PATH: process.env["RAVENS_MODELS_PATH"],
  RAVENS_DISABLE_EMBEDDED_WEB_UI: truthy("RAVENS_DISABLE_EMBEDDED_WEB_UI"),
  RAVENS_DB: process.env["RAVENS_DB"],
  RAVENS_DISABLE_CHANNEL_DB: truthy("RAVENS_DISABLE_CHANNEL_DB"),
  RAVENS_SKIP_MIGRATIONS: truthy("RAVENS_SKIP_MIGRATIONS"),
  RAVENS_STRICT_CONFIG_DEPS: truthy("RAVENS_STRICT_CONFIG_DEPS"),

  RAVENS_WORKSPACE_ID: process.env["RAVENS_WORKSPACE_ID"],
  RAVENS_EXPERIMENTAL_WORKSPACES: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_WORKSPACES"),
  RAVENS_EXPERIMENTAL_EVENT_SYSTEM: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_EVENT_SYSTEM"),
  RAVENS_EXPERIMENTAL_SESSION_SWITCHING: RAVENS_EXPERIMENTAL || truthy("RAVENS_EXPERIMENTAL_SESSION_SWITCHING"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get RAVENS_DISABLE_PROJECT_CONFIG() {
    return truthy("RAVENS_DISABLE_PROJECT_CONFIG")
  },
  get RAVENS_TUI_CONFIG() {
    return process.env["RAVENS_TUI_CONFIG"]
  },
  get RAVENS_CONFIG_DIR() {
    return process.env["RAVENS_CONFIG_DIR"]
  },
  get RAVENS_PURE() {
    return truthy("RAVENS_PURE")
  },
  get RAVENS_PLUGIN_META_FILE() {
    return process.env["RAVENS_PLUGIN_META_FILE"]
  },
  get RAVENS_CLIENT() {
    return process.env["RAVENS_CLIENT"] ?? "cli"
  },
}
